### ISSUE TITLE
Error messages related to "commonElements.mod"

### ISSUE THREAD

**Issue by nakohdo** [oasis-open/dita-rng-converter#14]
When validating against the generated DTDs for our customization I get error messages like the following:

```
System ID: \DITA-OT\plugins\org.oasis-open.dita.v1_3\dtd\base\dtd\commonElements.mod
Main validation file: parson_concept.dita
Engine name: Xerces
Severity: fatal
Description: The attribute type is required in the declaration of attribute "univ-atts" for element "data-about".
Start location: 609:46
```

I suspect it might have something to do with the following issues because we tried to modularize our RNG customization. 

- "This particular type of constraint does make me realize that I need to handle this case as part of the DITA 1.3 RNG-to-DTD transform, meaning I have to make sure that any constraint that overrides the attributes for an element also contains copies of all the parameter entities that correspond to the RNG attribute groups used by that element type. I don't think I had considered that case yet (it doesn't come up in the TC-defined constraint modules for strict task body and machinery task body constraints)."   
*Eliot Kimber*  
Source: [Including "%select-atts;" in topic constraint module](https://groups.yahoo.com/neo/groups/dita-users/conversations/topics/35372)
- [Inheritance in a domain specialization](https://groups.yahoo.com/neo/groups/dita-users/conversations/topics/22818)

Any pointers welcome.

Best regards,
Frank

**Comment by nakohdo** [comment]
This is how we implemented the chaining of includes:

```
par_concept.rng 
  > par_topicConstraintMod.rng 
     > par_commonTopicsConstraintMod.rng 
        > topicMod.rng 
           > commonElementsConstraintMod.rng + MetaDeclMod.rng
```

Frank

**Comment by drmacro** [comment]
This was a bug in how constraint modules were being processed it in that the code generated "element type name" entities for all defines in the module, not just those that are for element types.

I've fixed that bug but there is a larger issue which is that constraint modules need to include the declaration of any parameter entities they reference because the base declarations will always occur after the constraint module. I'm working on that in a separate issue.
